### ISSUE TITLE
DTD is prohibited in this XML document.

### ISSUE THREAD

**Issue by djeznik** [GSA/oscal-ssp-to-word#3]
Received the follow error when running the code.

Error: Upload status: The file could not be uploaded. The following error occured: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

**Comment by volpet2014** [comment]
OSCAL does not support DTD in schema.   Resolved with end user to remove DTD at top of document.
